vanilla:
  input_dim: 10000
  output_dim: 10000
  emb_dim: 512
  hidden_dim: 512
  pff_dim: 2048
  n_layers: 6
  n_heads: 8
  dropout_ratio: 0.1

light:
  input_dim: 10000
  output_dim: 10000
  emb_dim: 256
  hidden_dim: 512
  pff_dim: 2048
  n_layers: 6
  n_heads: 8
  dropout_ratio: 0.1